// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdsbumwtxkknyatexapx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkc2J1bXd0eGtrbnlhdGV4YXB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTEwNTQsImV4cCI6MjA3MTg4NzA1NH0.6-Y4xVu-5sENA4rNjDlmyJICHtPR9Jpzzlx8uhndFSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});